name: Build Linien
description: Build all linien packages

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Update pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install build dependencies
      shell: bash
      run: pip install build wheel

    - name: Build linien-common
      shell: bash
      working-directory: linien-common
      run: python -m build

    - name: Build linien-server
      shell: bash
      working-directory: linien-server
      run: python -m build

    - name: Build linien-client
      shell: bash
      working-directory: linien-client
      run: python -m build

    - name: Build linien-gui
      shell: bash
      working-directory: linien-gui
      run: python -m build
