name: Upload Packages to PyPI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: Build Linien
        uses: ./.github/actions/build-linien

      - name: Publish linien-common
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: linien-common/dist/
          password: ${{ secrets.PYPI_API_TOKEN_COMMON }}

      - name: Publish linien-server
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: linien-server/dist/
          password: ${{ secrets.PYPI_API_TOKEN_SERVER }}

      - name: Publish linien-client
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: linien-client/dist/
          password: ${{ secrets.PYPI_API_TOKEN_CLIENT }}

      - name: Publish linien-gui
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: linien-gui/dist/
          password: ${{ secrets.PYPI_API_TOKEN_GUI }}
