name: Pyinstaller Linux

on:
  workflow_dispatch:

env:
  QT_DEBUG_PLUGINS: 1
  DISPLAY: ":99"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install additional dependencies
        run: |
          sudo apt-get install -y qt5-default qttools5-dev-tools binutils libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libegl1-mesa
          pip install pyinstaller

      - name: Install linien-common
        working-directory: linien-common
        run: pip install .

      - name: Install linien-client
        working-directory: linien-client
        run: pip install .

      - name: Install linien-gui
        working-directory: linien-gui
        run: pip install .

      - run: pyinstaller pyinstaller.spec
        working-directory: linien-gui

      - uses: actions/upload-artifact@v4
        with:
          name: linien-gui-linux
          path: linien-gui/dist/*
