name: Pyinstaller Windows

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/pyinstaller-windows.yml
      - .github/actions/install-linien/**      
      - linien-common/**
      - linien-client/**
      - linien-gui/**

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Linien
        uses: ./.github/actions/install-linien

      - name: Install Pyinstaller
        run: pip install pyinstaller

      - run: pyinstaller pyinstaller.spec
        working-directory: linien-gui

      - uses: actions/upload-artifact@v4
        with:
          name: linien-gui-windows
          path: linien-gui/dist/*
